### ISSUE TITLE
Webmin hangs on connecting

### ISSUE THREAD

**Issue by vrogojin** [sameersbn/docker-bind#22]
Webmin just hangs on connecting:

```
vrogojin@wormhole:~$ wget localhost:10000
converted 'http://localhost:10000' (ANSI_X3.4-1968) -> 'http://localhost:10000' (UTF-8)
--2017-01-07 15:59:56--  http://localhost:10000/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:10000... connected.
HTTP request sent, awaiting response... 
```

IT HANGS HERE

Using docker-compose:
```
bind:
  image: sameersbn/bind:latest
  dns: 127.0.0.1
  environment:
    - ROOT_PASSWORD=SecretPassword
  ports:
   - 10000:10000
   - 53:53/udp
  volumes:
    - ./bind:/data
```
 
on Debian Jessie
