### ISSUE TITLE
Unable to start services

### ISSUE THREAD

**Issue by Daethe** [sameersbn/docker-bind#67]
I couldn't start container du to following error:

```
Attaching to binddns
binddns    | standard_init_linux.go:190: exec user process caused "exec format error"
binddns exited with code 1
```

I'm using the latest image version known has `sameersbn/bind:9.11.3-20190113`.
My docker-compose configuration is the following:

```
version: "3"
services:
    binddns:
        container_name: binddns
        domainname: binddns
        hostname: binddns
        image: sameersbn/bind:9.11.3-20190113
        ports:
            - 53:53/udp
            - 53:53/tcp
            - 8001:10000/tcp
        dns:
            - 127.0.0.1
        environment: 
            - ROOT_PASSWORD=${BIND_ROOT_PASSWORD}
        volumes:
            - ${PWD}/data/bind:/data
        labels:
            - traefik.enable=true
            - traefik.backend=webmin
            - traefik.port=10000
            - traefik.frontend.rule=HostRegexp:dns.proux.lan,{catchall:.*}
            - traefik.frontend.priority=1
            - traefik.frontend.headers.SSLRedirect=true
            - traefik.frontend.headers.STSSeconds=315360000
            - traefik.frontend.headers.browserXSSFilter=true
            - traefik.frontend.headers.contentTypeNosniff=true
            - traefik.frontend.headers.forceSTSHeader=true
            - traefik.frontend.headers.SSLHost=proux.lan
            - traefik.frontend.headers.STSIncludeSubdomains=true
            - traefik.frontend.headers.STSPreload=true
            - traefik.frontend.headers.frameDeny=true
        restart: always
```

---
`docker version`:
```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:10:06 2018
 OS/Arch:       linux/arm64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:08:10 2018
  OS/Arch:      linux/arm64
  Experimental: false
```

`docker info`:
```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 3.14.79-117
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: aarch64
CPUs: 4
Total Memory: 1.677GiB
Name: black-pearl
ID: 2XPL:RA4C:X4IR:4DTC:CBMT:PHZU:X2M5:2HAR:45H3:UVE7:OTN5:LHFM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
