### ISSUE TITLE
Cannot access dns server after applying configs ";; connection timed out; no servers could be reached"

### ISSUE THREAD

**Issue by snspinn** [sameersbn/docker-bind#74]
I have been trying to configure the BIND container as a private network DNS server (loosely) following the [DigitalOcean ](https://www.digitalocean.com/community/tutorials/how-to-configure-bind-as-a-private-network-dns-server-on-ubuntu-18-04) tutorial.
I have been been getting the error `;; connection timed out; no servers could be reached` once any configuration changes are applied.

As a debugging step I tried a "regular" install (service) of bind9. I am not getting the same issues if running a service (`systemctl start bind9`).

I think this is related to #65 
i.e. as a result of running `sudo systemctl stop systemd-resolved.service`.

My docker-compose:

```
version: '2'

services:
  bind:
    image: sameersbn/bind:latest
    dns: 127.0.0.1
    ports:
    - 192.168.88.76:53:53/udp
    - 192.168.88.76:53:53/tcp
    environment:
    - WEBMIN_ENABLED=false
    volumes:
    - /srv/docker/bind:/data
```

**Additional**
I am also seeing `sudo: unable to resolve host ubuntu: Resource temporarily unavailable` on the dns host when running the container.
