### ISSUE TITLE
Can not change SSL mode for webmin

### ISSUE THREAD

**Issue by jonasstrehle** [sameersbn/docker-bind#98]
I'm not getting **webmin** for **docker-bind** working. So I'm using **traefik** as proxy and listening on the dns.mydomain.com subdomain (SSL).

Navigating to the URI all I'm getting is a _502 Bad Gateway_ error message. Navigating inside the docker to the internal IP (`curl -G myinternalip:10000`) returns the error `This web server is running in SSL mode. Try the URL <a href='https://dns-main:10000/'>https://docker-bind:10000/</a> instead.`.

Note that in the running container the file /etc/webmin/miniserv.conf does not seems to be changed (SSL=1) instead of SSL=0. Adding a volume mount to override the file (./miniserv.conf:/etc/webmin/miniserv.conf) is not possible due to this error: `rm: cannot remove '/etc/webmin/miniserv.conf': Device or resource busy`

I'm not really sure how to go on ... so does anybody know how to fix this? Any help would be really appreciated.

docker-compose.yml service:
```
dns-bind:
    container_name: docker-bind
    restart: always
    image: sameersbn/bind:9.16.1-20200524
    hostname: docker-bind
    environment:
      - WEBMIN_INIT_SSL_ENABLED=false
      - WEBMIN_INIT_REFERERS=dns.mydomain.com
      - WEBMIN_ENABLED=true
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 10000:10000/tcp
    expose:
      - 10000
    volumes:
      - /srv/docker/bind:/data
      # - ./miniserv.conf:/etc/webmin/miniserv.conf
    networks:
      - main
    labels:
      - traefik.enable=true
      - traefik.port=10000
      - traefik.http.routers.dns.rule=Host(`dns.mydomain.com`)
      - traefik.http.routers.dns.entrypoints=web
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.dns.middlewares=redirect-to-https@docker
      - traefik.http.routers.dns-secured.rule=Host(`dns.mydomain.com`)
      - traefik.http.routers.dns-secured.tls=true
      - traefik.http.routers.dns-secured.tls.certresolver=myhttpchallenge
```
